name: pro_calc
description: "Pro Calc is a powerful calculator app that allows you to perform complex calculations with ease. With its intuitive interface and advanced features, Pro Calc is the perfect tool for students, professionals, and anyone who needs to perform complex calculations on the go."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  provider: ^6.1.4
  intl: ^0.20.0
  eval_ex: ^1.2.0

  # The core Flutter framework includes Material widgets.
  # material: ^0.0.1 # Removed - this is unnecessary and likely the wrong package.

  cupertino_icons: ^1.0.2
  
  fluentui_system_icons: ^1.1.229
  # math_expressions: ^2.7.0 # Note: Check pub.dev for the latest version if needed. Version 2.7.0 seems custom or old, 2.4.0 is common.
  function_tree: ^0.9.1
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # Added version constraint - check pub.dev for the latest
  test_api: ^0.7.4 # Moved from dependencies


flutter_native_splash:
  color: "#ffffff"
  image: lib/Assets/ProCalc Icon.png
  android: true
  ios: true
  android_12:
    image: lib/Assets/ProCalc Icon.png # Image for Android 12+ (can be same as legacy)
    color: "#ffffff"   

# Built flutter_native_splash:create.
# [Android] Creating default splash images
# [Android] Updating launch background(s) with splash image path...
# [Android]  - android/app/src/main/res/drawable/launch_background.xml
# [Android]  - android/app/src/main/res/drawable-v21/launch_background.xml
# [Android] Updating styles...
# [Android]  - android/app/src/main/res/values-v31/styles.xml
# [Android] No android/app/src/main/res/values-v31/styles.xml found in your Android project
# [Android] Creating android/app/src/main/res/values-v31/styles.xml and adding it to your Android project
# [Android]  - android/app/src/main/res/values-night-v31/styles.xml
# [Android] No android/app/src/main/res/values-night-v31/styles.xml found in your Android project
# [Android] Creating android/app/src/main/res/values-night-v31/styles.xml and adding it to your Android project
# [Android]  - android/app/src/main/res/values/styles.xml
# [Android]  - android/app/src/main/res/values-night/styles.xml
# [iOS] Creating  images
# [iOS] Updating ios/Runner/Info.plist for status bar hidden/visible
# [Web] Creating images
# [Web] Creating images
# [Web] Creating background images
# [Web] Creating CSS
# [Web] Updating index.html
  
# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon" # Can be true, false, or a specific file name like this.
  ios: true
  image_path: "lib/Assets/ProCalc Icon.png"
  web:
    generate: true
    image_path: "lib/Assets/ProCalc Icon.png"
  min_sdk_android: 21 # Optional: Specifies the minimum SDK level for generated adaptive icons

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # Example: Ensure your icon path is accessible if not using the default location.
  # assets:
  #  - lib/Assets/