name: pro_calc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.229
  math_expressions: ^2.7.0
  function_tree: ^0.9.1
  test_api: 0.7.4
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0  # Added for high refresh rate support

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
