name: pro_calc
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  provider: ^6.1.4
  intl: ^0.20.0
  eval_ex: ^1.2.0

  # The core Flutter framework includes Material widgets.
  # material: ^0.0.1 # Removed - this is unnecessary and likely the wrong package.

  cupertino_icons: ^1.0.2
  
  fluentui_system_icons: ^1.1.229
  # math_expressions: ^2.7.0 # Note: Check pub.dev for the latest version if needed. Version 2.7.0 seems custom or old, 2.4.0 is common.
  function_tree: ^0.9.1
  shared_preferences: ^2.2.2
  flutter_displaymode: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3 # Added version constraint - check pub.dev for the latest
  test_api: ^0.7.4 # Moved from dependencies

# Configuration for flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon" # Can be true, false, or a specific file name like this.
  ios: true
  image_path: "lib/Assets/ProCalc Icon.png"
  min_sdk_android: 21 # Optional: Specifies the minimum SDK level for generated adaptive icons

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # Example: Ensure your icon path is accessible if not using the default location.
  # assets:
  #  - lib/Assets/