name: Dev Branch APK Pre-release Build
on:
  # push:
  #   branches:
  #     - dev
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build (default: dev)'
        required: false
        default: 'dev'
jobs:
  build_and_prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'dev' }} # Use input branch or default to dev
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build Release APK
        run: flutter build apk --release
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/apk/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      - name: Find Signed APK
        id: find_signed_apk
        run: |
          SIGNED_APK=$(find build/app/outputs/apk/release -name "*-release-signed.apk" | head -n 1)
          if [ -z "$SIGNED_APK" ]; then
            echo "Signed APK not found!"
            exit 1
          fi
          echo "Signed APK found: $SIGNED_APK"
          echo "signed_apk_path=$SIGNED_APK" >> "$GITHUB_OUTPUT"
      - name: Create GitHub Pre-release and Upload APK
        if: ${{ steps.find_signed_apk.outputs.signed_apk_path != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: dev-build-${{ github.run_number }}
          name: Dev Build #${{ github.run_number }}
          body: |
            Pre-release build from ${{ github.event.inputs.branch || 'dev' }} branch.
            Triggered manually or on push (run #${{ github.run_number }}).
            Commit: ${{ github.sha }}
          prerelease: true
          draft: false
          files: ${{ steps.find_signed_apk.outputs.signed_apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
